line-length = 88
target-version = "py39"

[lint]
select = ["ALL"]

# https://docs.astral.sh/ruff/rules/
ignore = [
  "D203", # Docstring internal rule conflict
  "D212", # Docstring internal rule conflict
  "UP015", # Increase readability when opening with mode='r'
  "ANN101", # Ignore type requirement for self
  "N806", # Allow uppercase variables when it is constant
  "FA100", # x | Y annotations is >=Py3.10, FA100 asks __future__'s annotations, which gives X|Y
]

unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
